/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { CameraControls, Html, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import Welcome from "../pages/Welcome";
import About from "../pages/About";

export default function Desk(props) {
  const { nodes, materials } = useGLTF("/Adrian5.glb");
  const [activeScreen, setActiveScreen] = useState();
  const [active, setActive] = useState(false);
  const cameraRef = useRef();
  const RightTopMonitorScreen = useRef();
  const MiddleTopMonitorScreen = useRef();
  const LeftTopMonitorScreen = useRef();
  const LeftBottomMonitorScreen = useRef();
  const RightBottomMonitorScreen = useRef();

  const setMonitor = (ref) => {
    setActiveScreen(ref.current);
    setActive(true);

    if (cameraRef.current) {
      cameraRef.current.enabled = true;
    }
  };

  useFrame(() => {
    if (!active) {
      return;
    } else {
      cameraRef.current?.fitToBox(activeScreen, true);

      // const onRest = () => {
      //   if (cameraRef.current) {
      //     cameraRef.current.enabled = false;
      //     cameraRef.current.removeEventListener("rest", onRest);
      //   }
      // };
      // cameraRef.current.addEventListener("rest", onRest);
    }
  }, [activeScreen]);

  useEffect(() => {
    const handleKeyDown = (event) => {
      if (event.key === "Escape") {
        cameraRef.current?.reset(true);
        setActive(false);
      }
    };

    document.addEventListener("keydown", handleKeyDown);

    return () => {
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, []);

  return (
    <>
      <CameraControls
        minDistance={3}
        maxDistance={4}
        minPolarAngle={Math.PI / 4}
        maxPolarAngle={Math.PI / 2}
        minAzimuthAngle={-Math.PI / 6}
        maxAzimuthAngle={Math.PI / 6}
        ref={cameraRef}
      />
      <group {...props} dispose={null}>
        <group name="Scene">
          <mesh
            name="MonitorStand008"
            castShadow
            receiveShadow
            geometry={nodes.MonitorStand008.geometry}
            material={materials["Material.001"]}
            position={[-18.906, 2.171, -3.654]}
          />
          <mesh
            ref={LeftBottomMonitorScreen}
            name="LeftBottomMonitor001"
            castShadow
            receiveShadow
            geometry={nodes.LeftBottomMonitor001.geometry}
            material={materials["Material.001"]}
            position={[-20.106, 2.995, -3.679]}
            rotation={[1.507, 0.004, -0.166]}
            onClick={() => setMonitor(LeftBottomMonitorScreen)}
          >
            <Html
              occlude="blending"
              prepend
              center
              scale={0.98}
              position-y={0.1}
              rotation-x={-Math.PI / 2}
              transform
            >
              <About />
            </Html>
          </mesh>
          <mesh
            onClick={() => setMonitor(RightBottomMonitorScreen)}
            ref={RightBottomMonitorScreen}
            name="RightBottomMonitor001"
            castShadow
            receiveShadow
            geometry={nodes.RightBottomMonitor001.geometry}
            material={materials["Material.001"]}
            position={[-17.736, 2.995, -3.713]}
            rotation={[1.507, -0.008, 0.125]}
          >
            <Html
              occlude="blending"
              prepend
              center
              scale={0.98}
              position-y={0.2}
              rotation-x={-Math.PI / 2}
              transform
            >
              <About />
            </Html>
          </mesh>
          <mesh
            onClick={() => setMonitor(RightTopMonitorScreen)}
            ref={RightTopMonitorScreen}
            name="RightTopMonitor001"
            castShadow
            receiveShadow
            geometry={nodes.RightTopMonitor001.geometry}
            material={materials["Material.001"]}
            position={[-15.112, 4.526, -3.628]}
            rotation={[Math.PI / 2, 0, 0.175]}
          >
            <Html
              occlude="blending"
              prepend
              center
              scale={0.98}
              position-y={0.2}
              rotation-x={-Math.PI / 2}
              transform
            >
              <About />
            </Html>
          </mesh>
          <mesh
            onClick={() => setMonitor(LeftTopMonitorScreen)}
            ref={LeftTopMonitorScreen}
            name="LeftTopMonitor001"
            castShadow
            receiveShadow
            geometry={nodes.LeftTopMonitor001.geometry}
            material={materials["Material.001"]}
            position={[-22.65, 4.54, -3.651]}
            rotation={[Math.PI / 2, 0, -0.141]}
          >
            <Html
              occlude="blending"
              prepend
              center
              scale={0.98}
              position-y={0.2}
              rotation-x={-Math.PI / 2}
              transform
            >
              <About />
            </Html>
          </mesh>
          <mesh
            ref={MiddleTopMonitorScreen}
            name="MiddleTopMonitor001"
            castShadow
            receiveShadow
            geometry={nodes.MiddleTopMonitor001.geometry}
            material={materials["Material.001"]}
            position={[-18.868, 4.528, -3.865]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <Html
              prepend
              rotation-x={-Math.PI / 2}
              position={[0, 0.1, 0]}
              transform
              occlude
              scale={0.2}
            >
              <Welcome
                setMonitor={setMonitor}
                screenRef={MiddleTopMonitorScreen}
              />
            </Html>
          </mesh>
          <mesh
            name="MousePad001"
            castShadow
            receiveShadow
            geometry={nodes.MousePad001.geometry}
            material={materials.MousePad}
            position={[-18.999, 2.122, -2.689]}
            rotation={[-Math.PI, 1.568, -Math.PI]}
          />
          <mesh
            name="Mouse001"
            castShadow
            receiveShadow
            geometry={nodes.Mouse001.geometry}
            material={materials["Material.003"]}
            position={[-18.256, 2.178, -2.663]}
            rotation={[-Math.PI, 1.568, -Math.PI]}
          />
          <mesh
            name="Keyboard001"
            castShadow
            receiveShadow
            geometry={nodes.Keyboard001.geometry}
            material={materials.RigMaterial}
            position={[-19.438, 2.168, -2.925]}
            rotation={[-Math.PI, 1.568, -Math.PI]}
          >
            <mesh
              name="KeyCaps001"
              castShadow
              receiveShadow
              geometry={nodes.KeyCaps001.geometry}
              material={materials.KeYBOARD}
              position={[-0.037, 0.106, -0.688]}
              rotation={[0, 0, 0.086]}
            />
          </mesh>
          <mesh
            name="HeadphoneSTAND001"
            castShadow
            receiveShadow
            geometry={nodes.HeadphoneSTAND001.geometry}
            material={materials["Material.002"]}
            position={[-15.459, 2.179, -3.414]}
          />
          <group
            name="DeskHeadphone001"
            position={[-15.463, 2.448, -3.108]}
            rotation={[-2.914, 1.52, 2.931]}
          >
            <mesh
              name="Circle001"
              castShadow
              receiveShadow
              geometry={nodes.Circle001.geometry}
              material={materials.Headphones}
            />
            <mesh
              name="Circle001_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle001_1.geometry}
              material={materials.Foam}
            />
          </group>
          <group
            name="Book002"
            position={[-21.392, 2.198, -2.891]}
            scale={[1, 0.367, 1]}
          >
            <mesh
              name="Cube003"
              castShadow
              receiveShadow
              geometry={nodes.Cube003.geometry}
              material={materials.Redbook}
            />
            <mesh
              name="Cube003_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube003_1.geometry}
              material={materials.Paper}
            />
          </group>
          <group
            name="Book003"
            position={[-21.078, 2.213, -2.891]}
            rotation={[0.006, 0.006, -0.152]}
            scale={[0.96, 0.424, 1]}
          >
            <mesh
              name="Cube004"
              castShadow
              receiveShadow
              geometry={nodes.Cube004.geometry}
              material={materials.Book1}
            />
            <mesh
              name="Cube004_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube004_1.geometry}
              material={materials.Paper}
            />
          </group>
          <group name="Plane002" position={[-16.667, 2.142, -2.549]}>
            <mesh
              name="Plane040"
              castShadow
              receiveShadow
              geometry={nodes.Plane040.geometry}
              material={materials.Screen}
            />
            <mesh
              name="Plane040_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane040_1.geometry}
              material={materials["Iphone Gold"]}
            />
            <mesh
              name="Plane040_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane040_2.geometry}
              material={materials["Iphone BACK"]}
            />
            <mesh
              name="IphoneScreen001"
              castShadow
              receiveShadow
              geometry={nodes.IphoneScreen001.geometry}
              material={materials.Screen}
              position={[0, 0.001, 0]}
              scale={0.973}
            />
          </group>
          <mesh
            name="MonitorStand009"
            castShadow
            receiveShadow
            geometry={nodes.MonitorStand009.geometry}
            material={materials["Material.001"]}
            position={[-18.906, 2.171, -3.654]}
          />
          <mesh
            name="MonitorStand010"
            castShadow
            receiveShadow
            geometry={nodes.MonitorStand010.geometry}
            material={materials["Material.001"]}
            position={[-18.906, 2.171, -3.654]}
          />
          <mesh
            name="MonitorStand011"
            castShadow
            receiveShadow
            geometry={nodes.MonitorStand011.geometry}
            material={materials["Material.001"]}
            position={[-18.906, 2.171, -3.654]}
          />
          <mesh
            name="MonitorStand012"
            castShadow
            receiveShadow
            geometry={nodes.MonitorStand012.geometry}
            material={materials["Material.001"]}
            position={[-18.906, 2.171, -3.654]}
          />
          <mesh
            name="MonitorStand013"
            castShadow
            receiveShadow
            geometry={nodes.MonitorStand013.geometry}
            material={materials["Material.001"]}
            position={[-18.906, 2.171, -3.654]}
          />
          <mesh
            name="MonitorStand014"
            castShadow
            receiveShadow
            geometry={nodes.MonitorStand014.geometry}
            material={materials["Material.001"]}
            position={[-16.302, 2.171, -3.632]}
          />
          <mesh
            name="MonitorStand015"
            castShadow
            receiveShadow
            geometry={nodes.MonitorStand015.geometry}
            material={materials["Material.001"]}
            position={[-21.541, 2.171, -3.632]}
          />
          <mesh
            name="LeftBottomScreen001"
            castShadow
            receiveShadow
            geometry={nodes.LeftBottomScreen001.geometry}
            material={materials["Screen.001"]}
            position={[-20.106, 2.995, -3.677]}
            rotation={[1.507, 0.004, -0.166]}
          />
          <mesh
            name="RightTopScreen001"
            castShadow
            receiveShadow
            geometry={nodes.RightTopScreen001.geometry}
            material={materials["Screen.001"]}
            position={[-15.112, 4.526, -3.621]}
            rotation={[Math.PI / 2, 0, 0.175]}
          />
          <mesh
            name="MiddleTopScreen001"
            castShadow
            receiveShadow
            geometry={nodes.MiddleTopScreen001.geometry}
            material={materials["Screen.001"]}
            position={[-18.868, 4.528, -3.862]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="LeftTopScreen001"
            castShadow
            receiveShadow
            geometry={nodes.LeftTopScreen001.geometry}
            material={materials["Screen.001"]}
            position={[-22.65, 4.54, -3.65]}
            rotation={[Math.PI / 2, 0, -0.141]}
          />
          <group name="Table001_Baked" position={[-18.703, 1.877, -2.971]}>
            <mesh
              name="Plane081"
              castShadow
              receiveShadow
              geometry={nodes.Plane081.geometry}
              material={materials.wood_table_001}
            />
            <mesh
              name="Plane081_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane081_1.geometry}
              material={materials.Tableleg}
            />
          </group>
          <mesh
            name="RightBottomMonitor002"
            castShadow
            receiveShadow
            geometry={nodes.RightBottomMonitor002.geometry}
            material={materials.Screen}
            position={[-17.736, 2.995, -3.711]}
            rotation={[1.507, -0.008, 0.125]}
          />
          <group name="Plane001" position={[-19.036, 0, -3.098]}>
            <mesh
              name="Plane001_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane001_1.geometry}
              material={materials["Material.006"]}
            />
            <mesh
              name="Plane001_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane001_2.geometry}
              material={materials["Material.008"]}
            />
          </group>
          <group
            name="Katana_Stand_01"
            position={[-19.086, 6.518, -5.532]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <mesh
              name="katana_stand_01"
              castShadow
              receiveShadow
              geometry={nodes.katana_stand_01.geometry}
              material={materials.katana_stand_01}
              position={[0.287, 0, 0]}
              rotation={[-1.602, 0, 0]}
              scale={12.588}
            />
          </group>
          <group
            name="Sword"
            position={[-15.615, 8.04, -5.27]}
            rotation={[2.49, 0, 1.565]}
            scale={4.777}
          >
            <mesh
              name="Blade"
              castShadow
              receiveShadow
              geometry={nodes.Blade.geometry}
              material={materials.Blade}
            />
            <mesh
              name="Dół"
              castShadow
              receiveShadow
              geometry={nodes.Dół.geometry}
              material={materials.Dół}
            />
            <mesh
              name="Guard"
              castShadow
              receiveShadow
              geometry={nodes.Guard.geometry}
              material={materials.Guard}
            />
            <mesh
              name="Handle"
              castShadow
              receiveShadow
              geometry={nodes.Handle.geometry}
              material={materials.Handle}
            />
            <mesh
              name="Ring"
              castShadow
              receiveShadow
              geometry={nodes.Ring.geometry}
              material={materials.Handle}
            />
          </group>
          <mesh
            name="stone002"
            castShadow
            receiveShadow
            geometry={nodes.stone002.geometry}
            material={materials.stones}
            position={[-5.494, 3.13, -4.915]}
            rotation={[-2.582, -0.196, -2.448]}
            scale={0.442}
          />
          <group
            name="Modular_ficus_plant"
            position={[-25.859, 0, -3.092]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={2.981}
          >
            <mesh
              name="Cylinder006"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006.geometry}
              material={materials.Plastic}
              position={[0, 0.397, 0]}
              scale={3.229}
            />
            <mesh
              name="Leaf_2002"
              castShadow
              receiveShadow
              geometry={nodes.Leaf_2002.geometry}
              material={materials["Material.007"]}
              position={[-0.002, 0.566, -0.022]}
              rotation={[-Math.PI, 0.89, -Math.PI]}
              scale={0.153}
            />
            <group
              name="Operator_2002"
              position={[-0.002, 0.643, -0.003]}
              rotation={[Math.PI, -1.027, Math.PI]}
              scale={0.152}
            />
            <mesh
              name="Pot002"
              castShadow
              receiveShadow
              geometry={nodes.Pot002.geometry}
              material={materials["Glazed ceramic"]}
              position={[0, -0.004, -0.02]}
              scale={3.229}
            />
            <mesh
              name="Stem_2002"
              castShadow
              receiveShadow
              geometry={nodes.Stem_2002.geometry}
              material={materials["Material.005"]}
              position={[-0.004, 0.601, -0.002]}
              rotation={[-Math.PI, 0.92, -Math.PI]}
              scale={0.142}
            />
            <group
              name="stem_2002"
              position={[-0.002, 0.6, -0.003]}
              rotation={[-Math.PI, 0.92, -Math.PI]}
              scale={0.153}
            />
          </group>
          <group
            name="Modular_ficus_plant003"
            position={[-11.988, 0, -3.092]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={2.981}
          >
            <mesh
              name="Leaf_2001"
              castShadow
              receiveShadow
              geometry={nodes.Leaf_2001.geometry}
              material={materials["Material.010"]}
              position={[-0.002, 0.566, -0.022]}
              rotation={[-Math.PI, 0.89, -Math.PI]}
              scale={0.153}
            />
            <group
              name="Operator_2001"
              position={[-0.002, 0.643, -0.003]}
              rotation={[Math.PI, -1.027, Math.PI]}
              scale={0.152}
            />
            <mesh
              name="Pot001"
              castShadow
              receiveShadow
              geometry={nodes.Pot001.geometry}
              material={materials["Glazed ceramic.001"]}
              position={[0, -0.004, -0.02]}
              scale={3.229}
            />
            <group
              name="stem_2001"
              position={[-0.002, 0.6, -0.003]}
              rotation={[-Math.PI, 0.92, -Math.PI]}
              scale={0.153}
            />
            <mesh
              name="Stem_2001"
              castShadow
              receiveShadow
              geometry={nodes.Stem_2001.geometry}
              material={materials["Material.009"]}
              position={[-0.004, 0.601, -0.002]}
              rotation={[-Math.PI, 0.92, -Math.PI]}
              scale={0.142}
            />
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/Adrian5.glb");
