/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Perf } from "r3f-perf";

export default function Cloud(props) {
	const { nodes, materials } = useGLTF("/models/Cloud.glb");
	return (
		<>
			<group
				{...props}
				dispose={null}>
				<group name='Scene'>
					<group
						name='Platform'
						position={[-1.92, 0, -0.945]}>
						<mesh
							name='Plane_1'
							castShadow
							receiveShadow
							geometry={nodes.Plane_1.geometry}
							material={materials.Concrete}
						/>
						<mesh
							name='Plane_2'
							castShadow
							receiveShadow
							geometry={nodes.Plane_2.geometry}
							material={materials["Neon.001"]}
						/>
					</group>
					<mesh
						name='Building1'
						castShadow
						receiveShadow
						geometry={nodes.Building1.geometry}
						material={materials.Wall}
						position={[-1.356, 0.1, -0.75]}
					/>
					<mesh
						name='Pump_roof'
						castShadow
						receiveShadow
						geometry={nodes.Pump_roof.geometry}
						material={materials.Concrete}
						position={[-1.356, 0.1, -0.75]}
					/>
					<mesh
						name='Sign'
						castShadow
						receiveShadow
						geometry={nodes.Sign.geometry}
						material={materials.Concrete}
						position={[-1.479, 1.02, 1.609]}
						scale={[1, 1.194, 1]}
					/>
					<mesh
						name='Pillar'
						castShadow
						receiveShadow
						geometry={nodes.Pillar.geometry}
						material={materials.Concrete}
						position={[-0.964, 0.142, 2.012]}
					/>
					<mesh
						name='Pillar001'
						castShadow
						receiveShadow
						geometry={nodes.Pillar001.geometry}
						material={materials.Concrete}
						position={[-1.761, 0.142, 2.012]}
					/>
					<group
						name='Buidling_2'
						position={[-1.467, 1.149, -1.317]}
						scale={[0.728, 0.728, 0.747]}>
						<mesh
							name='Plane006_1'
							castShadow
							receiveShadow
							geometry={nodes.Plane006_1.geometry}
							material={materials.Concrete}
						/>
						<mesh
							name='Plane006_2'
							castShadow
							receiveShadow
							geometry={nodes.Plane006_2.geometry}
							material={materials.Ground}
						/>
						<mesh
							name='Plane006_3'
							castShadow
							receiveShadow
							geometry={nodes.Plane006_3.geometry}
							material={materials.WindowLight}
						/>
					</group>
					<mesh
						name='Building1001'
						castShadow
						receiveShadow
						geometry={nodes.Building1001.geometry}
						material={materials.Concrete}
						position={[-1.356, 0.1, -0.75]}
					/>
					<group
						name='Island'
						position={[2.476, 0, -0.605]}>
						<mesh
							name='Vert'
							castShadow
							receiveShadow
							geometry={nodes.Vert.geometry}
							material={materials.Ground}
						/>
						<mesh
							name='Vert_1'
							castShadow
							receiveShadow
							geometry={nodes.Vert_1.geometry}
							material={materials.Concrete}
						/>
					</group>
					<group
						name='Building1002'
						position={[-1.356, 0.1, -0.75]}>
						<mesh
							name='Plane008_1'
							castShadow
							receiveShadow
							geometry={nodes.Plane008_1.geometry}
							material={materials.Metal}
						/>
						<mesh
							name='Plane008_2'
							castShadow
							receiveShadow
							geometry={nodes.Plane008_2.geometry}
							material={materials.WindowLight}
						/>
					</group>
					<mesh
						name='Building1003'
						castShadow
						receiveShadow
						geometry={nodes.Building1003.geometry}
						material={materials.Wall}
						position={[-1.356, 0.1, -0.75]}
					/>
					<mesh
						name='Building1004'
						castShadow
						receiveShadow
						geometry={nodes.Building1004.geometry}
						material={nodes.Building1004.material}
						position={[-1.356, 0.1, -0.75]}
					/>
					<mesh
						name='Building1_LED'
						castShadow
						receiveShadow
						geometry={nodes.Building1_LED.geometry}
						material={materials["Neon.001"]}
						position={[-1.356, 0.1, -0.75]}
					/>
					<mesh
						name='Pump_roof_LED'
						castShadow
						receiveShadow
						geometry={nodes.Pump_roof_LED.geometry}
						material={materials["Neon.001"]}
						position={[-1.356, 0.1, -0.75]}
					/>
					<mesh
						name='Panels'
						castShadow
						receiveShadow
						geometry={nodes.Panels.geometry}
						material={nodes.Panels.material}
						position={[-1.033, 1.02, 0.87]}
						scale={0.192}
					/>
					<mesh
						name='Sign001'
						castShadow
						receiveShadow
						geometry={nodes.Sign001.geometry}
						material={materials["Neon.001"]}
						position={[-1.479, 1.02, 1.609]}
						scale={[1, 1.194, 1]}
					/>
					<group
						name='Pumps_curb'
						position={[-1.304, 0.142, 1.734]}>
						<mesh
							name='Plane015'
							castShadow
							receiveShadow
							geometry={nodes.Plane015.geometry}
							material={materials.Concrete}
						/>
						<mesh
							name='Plane015_1'
							castShadow
							receiveShadow
							geometry={nodes.Plane015_1.geometry}
							material={materials.Neon}
						/>
					</group>
					<mesh
						name='Buidling_2001'
						castShadow
						receiveShadow
						geometry={nodes.Buidling_2001.geometry}
						material={materials.Ground}
						position={[-1.467, 1.149, -1.317]}
						scale={[0.728, 0.728, 0.747]}
					/>
					<mesh
						name='Buidling_2002'
						castShadow
						receiveShadow
						geometry={nodes.Buidling_2002.geometry}
						material={materials.Ground}
						position={[-1.467, 1.149, -1.317]}
						scale={[0.728, 0.728, 0.747]}
					/>
					<group
						name='Buidling_2003'
						position={[-1.467, 1.149, -1.317]}
						scale={[0.728, 0.728, 0.747]}>
						<mesh
							name='Plane019'
							castShadow
							receiveShadow
							geometry={nodes.Plane019.geometry}
							material={materials.White}
						/>
						<mesh
							name='Plane019_1'
							castShadow
							receiveShadow
							geometry={nodes.Plane019_1.geometry}
							material={materials.Red}
						/>
					</group>
					<mesh
						name='Building2_Roof001'
						castShadow
						receiveShadow
						geometry={nodes.Building2_Roof001.geometry}
						material={materials.BlueMetal}
						position={[-1.473, 2.032, -1.215]}
						rotation={[0.2, 0, 0]}
						scale={[0.788, 0.793, 0.91]}
					/>
					<mesh
						name='Building2_Roof'
						castShadow
						receiveShadow
						geometry={nodes.Building2_Roof.geometry}
						material={materials.BlueMetal}
						position={[-1.274, 2.129, -1.507]}
						rotation={[0.199, -0.191, -0.015]}
						scale={[0.788, 0.793, 0.91]}
					/>
					<mesh
						name='Stairs'
						castShadow
						receiveShadow
						geometry={nodes.Stairs.geometry}
						material={materials["Metal.002"]}
						position={[0.161, 1.083, -1.801]}
						scale={[1, 1, 0.951]}
					/>
					<mesh
						name='Railing'
						castShadow
						receiveShadow
						geometry={nodes.Railing.geometry}
						material={materials["Metal.002"]}
						position={[0.161, 1.083, -1.801]}
						scale={[1, 1, 0.951]}
					/>
					<mesh
						name='Railing001'
						castShadow
						receiveShadow
						geometry={nodes.Railing001.geometry}
						material={materials["Metal.002"]}
						position={[-1.92, 0.352, -0.945]}
					/>
					<mesh
						name='Wireframe001'
						castShadow
						receiveShadow
						geometry={nodes.Wireframe001.geometry}
						material={materials["Metal.002"]}
						position={[-1.437, -0.09, -0.767]}>
						<mesh
							name='Plane'
							castShadow
							receiveShadow
							geometry={nodes.Plane.geometry}
							material={materials["Metal.003"]}
							position={[-0.755, 0.09, -0.076]}
							rotation={[-Math.PI, 1.571, 0]}
							scale={0.818}
						/>
						<mesh
							name='Plane001'
							castShadow
							receiveShadow
							geometry={nodes.Plane001.geometry}
							material={materials["Metal.003"]}
							position={[-0.101, 0.09, -0.076]}
							rotation={[-Math.PI, -1.571, 0]}
							scale={0.818}
						/>
						<mesh
							name='Plane003'
							castShadow
							receiveShadow
							geometry={nodes.Plane003.geometry}
							material={materials["Metal.003"]}
							position={[0.733, 0.09, 0.436]}
							rotation={[0, 0, Math.PI]}
							scale={0.793}
						/>
						<mesh
							name='Plane004'
							castShadow
							receiveShadow
							geometry={nodes.Plane004.geometry}
							material={materials["Metal.003"]}
							position={[0.943, -0.656, -0.557]}
							rotation={[Math.PI / 2, Math.PI / 2, 0]}
							scale={0.619}
						/>
						<mesh
							name='Tank001'
							castShadow
							receiveShadow
							geometry={nodes.Tank001.geometry}
							material={materials["Metal.003"]}
							position={[-0.169, -0.279, 0.344]}
							rotation={[-Math.PI, 0, 0]}
							scale={0.929}
						/>
						<mesh
							name='Tank006'
							castShadow
							receiveShadow
							geometry={nodes.Tank006.geometry}
							material={materials.Metal}
							position={[0.765, -0.186, -0.098]}
							rotation={[Math.PI / 2, 0, 0]}
							scale={0.792}
						/>
						<mesh
							name='Tank007'
							castShadow
							receiveShadow
							geometry={nodes.Tank007.geometry}
							material={materials["Metal.003"]}
							position={[-0.297, -0.444, 0.344]}
							rotation={[-Math.PI, 0, Math.PI / 2]}
							scale={0.893}
						/>
						<mesh
							name='Tank008'
							castShadow
							receiveShadow
							geometry={nodes.Tank008.geometry}
							material={materials.Metal}
							position={[0.136, -0.595, 0.215]}
							rotation={[Math.PI / 2, -Math.PI / 2, 0]}
							scale={0.416}
						/>
						<mesh
							name='Tank009'
							castShadow
							receiveShadow
							geometry={nodes.Tank009.geometry}
							material={materials.Metal}
							position={[0.466, -0.18, -0.514]}
							rotation={[0, 0, Math.PI]}
							scale={0.884}
						/>
					</mesh>
					<mesh
						name='Wireframe'
						castShadow
						receiveShadow
						geometry={nodes.Wireframe.geometry}
						material={materials["Metal.001"]}
						position={[-0.895, -0.028, 1.278]}
						scale={[1, 1.157, 0.791]}
					/>
					<group
						name='PowerSource'
						position={[0.836, 0.1, -0.714]}>
						<mesh
							name='Plane028'
							castShadow
							receiveShadow
							geometry={nodes.Plane028.geometry}
							material={materials["Metal.002"]}
						/>
						<mesh
							name='Plane028_1'
							castShadow
							receiveShadow
							geometry={nodes.Plane028_1.geometry}
							material={materials.Neon}
						/>
						<mesh
							name='Propeller'
							castShadow
							receiveShadow
							geometry={nodes.Propeller.geometry}
							material={materials["Metal.001"]}
							position={[0.023, 0.308, 0]}
						/>
					</group>
					<group
						name='ArrowPole'
						position={[2.519, -0.103, -0.619]}>
						<mesh
							name='Circle002'
							castShadow
							receiveShadow
							geometry={nodes.Circle002.geometry}
							material={materials.Concrete}
						/>
						<mesh
							name='Circle002_1'
							castShadow
							receiveShadow
							geometry={nodes.Circle002_1.geometry}
							material={materials["Metal.002"]}
						/>
						<mesh
							name='Circle002_2'
							castShadow
							receiveShadow
							geometry={nodes.Circle002_2.geometry}
							material={materials["Warning Light"]}
						/>
						<mesh
							name='Arrow_Sign'
							castShadow
							receiveShadow
							geometry={nodes.Arrow_Sign.geometry}
							material={materials.Rubber}
							position={[-0.15, 0.712, 0.042]}
							scale={[1, 1.289, 1]}
						/>
						<mesh
							name='Arrow001'
							castShadow
							receiveShadow
							geometry={nodes.Arrow001.geometry}
							material={materials["Neon.001"]}
							position={[-0.15, 0.712, 0.042]}
							scale={[1, 1.289, 1]}
						/>
						<mesh
							name='Arrow'
							castShadow
							receiveShadow
							geometry={nodes.Arrow.geometry}
							material={materials["Neon.001"]}
							position={[-0.477, 0.712, 0.079]}
						/>
					</group>
					<mesh
						name='Pump'
						castShadow
						receiveShadow
						geometry={nodes.Pump.geometry}
						material={materials.Red}
						position={[-0.926, 0.175, 1.694]}>
						<mesh
							name='pump'
							castShadow
							receiveShadow
							geometry={nodes.pump.geometry}
							material={materials.Metal}
							position={[-0.033, 0.279, -0.042]}
						/>
						<mesh
							name='pump001'
							castShadow
							receiveShadow
							geometry={nodes.pump001.geometry}
							material={materials.BlueMetal}
							position={[0, 0.411, 0]}
						/>
						<group
							name='pump002'
							position={[0, 0.522, 0]}
							scale={1.778}>
							<mesh
								name='Cylinder002'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder002.geometry}
								material={materials.Red}
							/>
							<mesh
								name='Cylinder002_1'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder002_1.geometry}
								material={materials.BlueMetal}
							/>
							<mesh
								name='Cylinder002_2'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder002_2.geometry}
								material={materials.Metal}
							/>
						</group>
					</mesh>
					<mesh
						name='Pump002'
						castShadow
						receiveShadow
						geometry={nodes.Pump002.geometry}
						material={materials.Red}
						position={[-1.655, 0.175, 1.694]}>
						<mesh
							name='pump005'
							castShadow
							receiveShadow
							geometry={nodes.pump005.geometry}
							material={materials.Metal}
							position={[-0.033, 0.279, -0.042]}
						/>
						<mesh
							name='pump006'
							castShadow
							receiveShadow
							geometry={nodes.pump006.geometry}
							material={materials.BlueMetal}
							position={[0, 0.411, 0]}
						/>
						<group
							name='pump007'
							position={[0, 0.522, 0]}
							scale={1.778}>
							<mesh
								name='Cylinder002'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder002.geometry}
								material={materials.Red}
							/>
							<mesh
								name='Cylinder002_1'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder002_1.geometry}
								material={materials.BlueMetal}
							/>
							<mesh
								name='Cylinder002_2'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder002_2.geometry}
								material={materials.Metal}
							/>
						</group>
					</mesh>
					<mesh
						name='Pump003'
						castShadow
						receiveShadow
						geometry={nodes.Pump003.geometry}
						material={materials.Red}
						position={[-1.311, 0.175, 1.694]}>
						<mesh
							name='pump008'
							castShadow
							receiveShadow
							geometry={nodes.pump008.geometry}
							material={materials.Metal}
							position={[-0.033, 0.279, -0.042]}
						/>
						<mesh
							name='pump009'
							castShadow
							receiveShadow
							geometry={nodes.pump009.geometry}
							material={materials.BlueMetal}
							position={[0, 0.411, 0]}
						/>
						<group
							name='pump010'
							position={[0, 0.522, 0]}
							scale={1.778}>
							<mesh
								name='Cylinder002'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder002.geometry}
								material={materials.Red}
							/>
							<mesh
								name='Cylinder002_1'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder002_1.geometry}
								material={materials.BlueMetal}
							/>
							<mesh
								name='Cylinder002_2'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder002_2.geometry}
								material={materials.Metal}
							/>
						</group>
					</mesh>
					<mesh
						name='Pipe001'
						castShadow
						receiveShadow
						geometry={nodes.Pipe001.geometry}
						material={materials.Chrome}
						position={[1.382, 0.1, -0.461]}
					/>
					<mesh
						name='Pipe003'
						castShadow
						receiveShadow
						geometry={nodes.Pipe003.geometry}
						material={materials["Metal.001"]}
						position={[0.857, 0.27, -0.335]}
					/>
					<mesh
						name='Pipe004'
						castShadow
						receiveShadow
						geometry={nodes.Pipe004.geometry}
						material={materials["Metal.003"]}
						position={[-0.895, 0.051, 1.242]}
					/>
					<mesh
						name='Pipe002'
						castShadow
						receiveShadow
						geometry={nodes.Pipe002.geometry}
						material={materials["Metal.001"]}
						position={[-0.898, -0.02, 1.352]}
					/>
					<group
						name='Pipe'
						position={[-0.877, 0.051, 1.323]}>
						<mesh
							name='Vert005'
							castShadow
							receiveShadow
							geometry={nodes.Vert005.geometry}
							material={materials["Metal.001"]}
						/>
						<mesh
							name='Vert005_1'
							castShadow
							receiveShadow
							geometry={nodes.Vert005_1.geometry}
							material={materials["Warning Light"]}
						/>
					</group>
					<mesh
						name='Box001'
						castShadow
						receiveShadow
						geometry={nodes.Box001.geometry}
						material={materials["Metal.003"]}
						position={[-0.621, 0, -1.326]}
						rotation={[0, 0, Math.PI]}
						scale={0.633}
					/>
					<mesh
						name='Tank004'
						castShadow
						receiveShadow
						geometry={nodes.Tank004.geometry}
						material={materials.Metal}
						position={[0.873, -0.27, -0.654]}
						rotation={[0, 0, Math.PI]}
						scale={0.721}
					/>
					<mesh
						name='Tank005'
						castShadow
						receiveShadow
						geometry={nodes.Tank005.geometry}
						material={materials.Metal}
						position={[0.873, -0.275, -1.258]}
						scale={0.714}
					/>
					<mesh
						name='Box'
						castShadow
						receiveShadow
						geometry={nodes.Box.geometry}
						material={materials["Metal.003"]}
						position={[0.862, -0.039, -1.721]}
						rotation={[-Math.PI, 0, 0]}
						scale={0.619}
					/>
					<mesh
						name='Wireframe002'
						castShadow
						receiveShadow
						geometry={nodes.Wireframe002.geometry}
						material={materials["Metal.002"]}
						position={[-1.036, -0.09, 2.069]}
						rotation={[-Math.PI, 0, -Math.PI]}
						scale={[0.756, 0.697, 0.697]}>
						<mesh
							name='Plane006'
							castShadow
							receiveShadow
							geometry={nodes.Plane006.geometry}
							material={materials["Metal.003"]}
							position={[-0.885, 0.128, -0.076]}
							rotation={[-Math.PI, 1.571, 0]}
							scale={0.936}
						/>
						<mesh
							name='Plane007'
							castShadow
							receiveShadow
							geometry={nodes.Plane007.geometry}
							material={materials["Metal.003"]}
							position={[-0.101, 0.09, -0.076]}
							rotation={[-Math.PI, -1.571, 0]}
							scale={0.818}
						/>
						<mesh
							name='Plane008'
							castShadow
							receiveShadow
							geometry={nodes.Plane008.geometry}
							material={materials["Metal.003"]}
							position={[0.817, 0.128, 0.509]}
							rotation={[0, 0, Math.PI]}
							scale={0.907}
						/>
						<mesh
							name='Tank002'
							castShadow
							receiveShadow
							geometry={nodes.Tank002.geometry}
							material={materials["Metal.003"]}
							position={[-0.512, -0.294, -0.46]}
							rotation={[1.604, 0, 0]}
							scale={1.063}
						/>
						<mesh
							name='Tank003'
							castShadow
							receiveShadow
							geometry={nodes.Tank003.geometry}
							material={materials.Metal}
							position={[0.853, -0.187, -0.101]}
							rotation={[Math.PI / 2, 0, 0]}
							scale={0.906}
						/>
						<mesh
							name='Tank011'
							castShadow
							receiveShadow
							geometry={nodes.Tank011.geometry}
							material={materials.Metal}
							position={[0.133, -0.655, 0.257]}
							rotation={[Math.PI / 2, -Math.PI / 2, 0]}
							scale={0.476}
						/>
						<mesh
							name='Tank012'
							castShadow
							receiveShadow
							geometry={nodes.Tank012.geometry}
							material={materials.Metal}
							position={[0.511, -0.181, -0.577]}
							rotation={[0, 0, Math.PI]}
							scale={1.011}
						/>
					</mesh>
					<mesh
						name='Text'
						castShadow
						receiveShadow
						geometry={nodes.Text.geometry}
						material={materials.Neon}
						position={[-1.324, 1.592, 1.692]}
						rotation={[Math.PI / 2, 0, -Math.PI / 2]}
						scale={0.198}
					/>
					<mesh
						name='Text001'
						castShadow
						receiveShadow
						geometry={nodes.Text001.geometry}
						material={materials["Neon.001"]}
						position={[-1.324, 1.842, 1.692]}
						rotation={[Math.PI / 2, 0, -Math.PI / 2]}
						scale={0.273}
					/>
					<mesh
						name='Text002'
						castShadow
						receiveShadow
						geometry={nodes.Text002.geometry}
						material={materials.Neon}
						position={[-0.735, 1.691, -1.036]}
						rotation={[1.618, 0, -Math.PI / 2]}
						scale={0.157}
					/>
					<mesh
						name='Text003'
						castShadow
						receiveShadow
						geometry={nodes.Text003.geometry}
						material={materials["Neon.002"]}
						position={[-0.629, 0.968, 1.352]}
						rotation={[Math.PI / 2, 0, -Math.PI / 2]}
						scale={0.18}
					/>
					<group
						name='Bilboard'
						position={[-1.437, 2.006, -1.153]}>
						<mesh
							name='Plane034'
							castShadow
							receiveShadow
							geometry={nodes.Plane034.geometry}
							material={materials["Metal.001"]}
						/>
						<mesh
							name='Plane034_1'
							castShadow
							receiveShadow
							geometry={nodes.Plane034_1.geometry}
							material={materials["Neon.001"]}
						/>
					</group>
					<mesh
						name='Bilboard_pole'
						castShadow
						receiveShadow
						geometry={nodes.Bilboard_pole.geometry}
						material={nodes.Bilboard_pole.material}
						position={[-1.437, 2.044, -1.131]}
					/>
					<mesh
						name='Barrel'
						castShadow
						receiveShadow
						geometry={nodes.Barrel.geometry}
						material={materials["Metal.001"]}
						position={[-0.235, 0.195, 2.493]}
						scale={0.291}
					/>
					<mesh
						name='Barrel001'
						castShadow
						receiveShadow
						geometry={nodes.Barrel001.geometry}
						material={materials["Metal.001"]}
						position={[-0.157, 0.195, 2.301]}
						scale={0.291}
					/>
					<mesh
						name='Tires'
						castShadow
						receiveShadow
						geometry={nodes.Tires.geometry}
						material={materials.Rubber}
						position={[-0.437, 0.196, 2.441]}
						scale={0.303}
					/>
					<group
						name='Streetlamp1'
						position={[-0.337, 0.142, 1.471]}
						rotation={[0, Math.PI / 2, 0]}
						scale={0.262}>
						<mesh
							name='Cylinder082'
							castShadow
							receiveShadow
							geometry={nodes.Cylinder082.geometry}
							material={materials["Metal.002"]}
						/>
						<mesh
							name='Cylinder082_1'
							castShadow
							receiveShadow
							geometry={nodes.Cylinder082_1.geometry}
							material={materials.Lamp}
						/>
						<mesh
							name='Cylinder082_2'
							castShadow
							receiveShadow
							geometry={nodes.Cylinder082_2.geometry}
							material={materials.TrafficGreen}
						/>
						<mesh
							name='Cylinder082_3'
							castShadow
							receiveShadow
							geometry={nodes.Cylinder082_3.geometry}
							material={materials["Traffic Yellow"]}
						/>
						<mesh
							name='Cylinder082_4'
							castShadow
							receiveShadow
							geometry={nodes.Cylinder082_4.geometry}
							material={materials["TrafficRed.001"]}
						/>
					</group>
					<mesh
						name='Streetpole'
						castShadow
						receiveShadow
						geometry={nodes.Streetpole.geometry}
						material={materials.Ground}
						position={[-2.576, 1.159, -1.85]}
						scale={[0.523, 0.408, 0.523]}
					/>
					<mesh
						name='Boxes'
						castShadow
						receiveShadow
						geometry={nodes.Boxes.geometry}
						material={nodes.Boxes.material}
						position={[-0.605, 1.157, -0.796]}
						scale={0.426}
					/>
					<group
						name='Trashcan002'
						position={[-2.419, 1.162, -0.809]}
						scale={0.335}>
						<mesh
							name='Cylinder006'
							castShadow
							receiveShadow
							geometry={nodes.Cylinder006.geometry}
							material={materials.Metal}
						/>
						<mesh
							name='Cylinder006_1'
							castShadow
							receiveShadow
							geometry={nodes.Cylinder006_1.geometry}
							material={materials.Paper}
						/>
						<mesh
							name='Cylinder006_2'
							castShadow
							receiveShadow
							geometry={nodes.Cylinder006_2.geometry}
							material={materials.Cardboard}
						/>
					</group>
					<group
						name='car'
						position={[0.344, -0.225, 0.717]}
						rotation={[0, -Math.PI / 2, 0]}
						scale={[0.519, 0.469, 0.469]}>
						<mesh
							name='Vert003_1'
							castShadow
							receiveShadow
							geometry={nodes.Vert003_1.geometry}
							material={materials.BlueMetal}
						/>
						<mesh
							name='Vert003_2'
							castShadow
							receiveShadow
							geometry={nodes.Vert003_2.geometry}
							material={materials.Window}
						/>
						<mesh
							name='Vert003_3'
							castShadow
							receiveShadow
							geometry={nodes.Vert003_3.geometry}
							material={materials.Chrome}
						/>
						<mesh
							name='Vert003_4'
							castShadow
							receiveShadow
							geometry={nodes.Vert003_4.geometry}
							material={materials.Headlights}
						/>
						<mesh
							name='Vert003_5'
							castShadow
							receiveShadow
							geometry={nodes.Vert003_5.geometry}
							material={materials.Chrome}
						/>
						<mesh
							name='Vert003_6'
							castShadow
							receiveShadow
							geometry={nodes.Vert003_6.geometry}
							material={materials.TailLight}
						/>
						<mesh
							name='DoorHandle'
							castShadow
							receiveShadow
							geometry={nodes.DoorHandle.geometry}
							material={nodes.DoorHandle.material}
						/>
						<group
							name='Engine'
							position={[0, 0, 0.095]}>
							<mesh
								name='Cylinder005'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder005.geometry}
								material={materials.Metal}
							/>
							<mesh
								name='Cylinder005_1'
								castShadow
								receiveShadow
								geometry={nodes.Cylinder005_1.geometry}
								material={materials.Neon}
							/>
						</group>
						<mesh
							name='FrontBumper'
							castShadow
							receiveShadow
							geometry={nodes.FrontBumper.geometry}
							material={materials.Metal}
						/>
						<mesh
							name='RearBumper'
							castShadow
							receiveShadow
							geometry={nodes.RearBumper.geometry}
							material={materials.Metal}
						/>
					</group>
				</group>
			</group>
		</>
	);
}

useGLTF.preload("/models/Cloud.glb");
