/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Park(props) {
	const { nodes, materials } = useGLTF("/models/SunnyPark.glb");
	return (
		<group
			{...props}
			dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Ground.geometry}
				material={materials.Ground}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass001.geometry}
				material={materials.Grass}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass002.geometry}
				material={materials.Grass}
				position={[2.943, 0, -2.97]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Bridge.geometry}
				material={materials["Rock.001"]}
				position={[-0.008, 0, -0.017]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane001.geometry}
					material={materials.Wood2}
					position={[0, 0.548, 0]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane002.geometry}
					material={materials.wood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane003.geometry}
					material={materials.Rock}
				/>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tree.geometry}
				material={materials.wood}
				position={[-2.979, 0.099, 3.175]}
				scale={1.852}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube.geometry}
					material={materials.Tree}
					position={[-0.364, 1.648, 0.364]}
					rotation={[0.147, 0.21, 0.244]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube001.geometry}
					material={materials.Tree}
					position={[0.259, 1.487, 0.051]}
					rotation={[1.344, -0.708, 0.97]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube002.geometry}
					material={materials.Tree}
					position={[-0.459, 0.999, 0.421]}
					rotation={[2.127, -0.025, 2.575]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube003.geometry}
					material={materials.Tree}
					position={[0.463, 1.134, 0.107]}
					rotation={[0.522, -0.097, 0.203]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube004.geometry}
					material={materials.Tree}
					position={[-0.026, 1.462, -0.506]}
					rotation={[2.786, -0.822, -2.904]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube005.geometry}
					material={materials.Tree}
					position={[0.291, 1.165, -0.568]}
					rotation={[1.626, -0.125, 2.449]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube006.geometry}
					material={materials.Tree}
					position={[0.114, 1.423, -0.216]}
					rotation={[2.786, -0.822, -2.904]}
					scale={1.264}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube007.geometry}
					material={materials.Tree}
					position={[-0.137, 1.414, 0.119]}
					rotation={[1.476, -0.925, 1.461]}
					scale={1.274}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube008.geometry}
					material={materials.Tree}
					position={[-0.012, 1.191, -0.061]}
					rotation={[1.476, -0.925, 1.461]}
					scale={0.876}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube009.geometry}
					material={materials.Tree}
					position={[-0.126, 1.101, 0.205]}
					rotation={[1.476, -0.925, 1.461]}
					scale={0.795}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube010.geometry}
					material={materials.Tree}
					position={[0.193, 1.271, 0.255]}
					rotation={[1.344, -0.708, 0.97]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube011.geometry}
					material={materials.Tree}
					position={[-0.008, 1.417, 0.45]}
					rotation={[1.344, -0.708, 0.97]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube012.geometry}
					material={materials.Tree}
					position={[-0.302, 1.318, 0.38]}
					rotation={[1.344, -0.708, 0.97]}
					scale={-0.887}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube013.geometry}
					material={materials.Tree}
					position={[-0.127, 1.225, -0.161]}
					rotation={[1.476, -0.925, 1.461]}
					scale={1.274}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube014.geometry}
					material={materials.Tree}
					position={[-0.081, 1.683, 0.119]}
					rotation={[1.476, -0.925, 1.461]}
					scale={1.274}
				/>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tree001.geometry}
				material={materials.wood}
				position={[-3.272, 0.218, -3.607]}
				scale={1.773}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube015.geometry}
					material={materials.Tree}
					position={[-0.364, 1.648, 0.364]}
					rotation={[0.147, 0.21, 0.244]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube016.geometry}
					material={materials.Tree}
					position={[0.259, 1.487, 0.051]}
					rotation={[1.344, -0.708, 0.97]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube017.geometry}
					material={materials.Tree}
					position={[-0.459, 0.999, 0.421]}
					rotation={[2.127, -0.025, 2.575]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube018.geometry}
					material={materials.Tree}
					position={[0.463, 1.134, 0.107]}
					rotation={[0.522, -0.097, 0.203]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube019.geometry}
					material={materials.Tree}
					position={[-0.026, 1.462, -0.506]}
					rotation={[2.786, -0.822, -2.904]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube020.geometry}
					material={materials.Tree}
					position={[0.291, 1.165, -0.568]}
					rotation={[1.626, -0.125, 2.449]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube021.geometry}
					material={materials.Tree}
					position={[0.114, 1.423, -0.216]}
					rotation={[2.786, -0.822, -2.904]}
					scale={1.264}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube022.geometry}
					material={materials.Tree}
					position={[-0.137, 1.414, 0.119]}
					rotation={[1.476, -0.925, 1.461]}
					scale={1.274}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube023.geometry}
					material={materials.Tree}
					position={[-0.012, 1.191, -0.061]}
					rotation={[1.476, -0.925, 1.461]}
					scale={0.876}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube024.geometry}
					material={materials.Tree}
					position={[-0.126, 1.101, 0.205]}
					rotation={[1.476, -0.925, 1.461]}
					scale={0.795}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube025.geometry}
					material={materials.Tree}
					position={[0.193, 1.271, 0.255]}
					rotation={[1.344, -0.708, 0.97]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube026.geometry}
					material={materials.Tree}
					position={[-0.008, 1.417, 0.45]}
					rotation={[1.344, -0.708, 0.97]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube027.geometry}
					material={materials.Tree}
					position={[-0.302, 1.318, 0.38]}
					rotation={[1.344, -0.708, 0.97]}
					scale={-0.887}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube028.geometry}
					material={materials.Tree}
					position={[-0.127, 1.225, -0.161]}
					rotation={[1.476, -0.925, 1.461]}
					scale={1.274}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube029.geometry}
					material={materials.Tree}
					position={[-0.081, 1.683, 0.119]}
					rotation={[1.476, -0.925, 1.461]}
					scale={1.274}
				/>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rock.geometry}
				material={materials.Rock}
				position={[-2.514, 0.092, 2.868]}
				scale={0.933}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rock003.geometry}
				material={materials.Rock}
				position={[-1.639, 0.099, 1.155]}
				scale={0.479}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rock004.geometry}
				material={materials.Rock}
				position={[-1.89, -0.5, -1.304]}
				scale={0.664}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rock005.geometry}
				material={materials.Rock}
				position={[-2.661, -0.495, 0.963]}
				scale={0.664}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rock006.geometry}
				material={materials.Rock}
				position={[-0.755, -0.467, 0.78]}
				scale={0.781}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rock007.geometry}
				material={materials.Rock}
				position={[2.458, -0.5, 0.202]}
				rotation={[-0.206, 0.991, -0.099]}
				scale={0.69}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rock008.geometry}
				material={materials.Rock}
				position={[1.539, -0.5, -1.082]}
				scale={0.458}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube039.geometry}
				material={materials.Rock}
				position={[0.504, -0.5, 0.746]}
				scale={0.279}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rock009.geometry}
				material={materials.Rock}
				position={[1.798, -0.5, -1.276]}
				scale={0.297}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Rock010.geometry}
				material={materials.Rock}
				position={[1.923, 0.099, -2.283]}
				rotation={[1.446, -0.005, -0.713]}
				scale={0.766}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass003.geometry}
				material={materials.Tree}
				position={[3.772, 0.099, 3.78]}
				scale={1.256}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass010.geometry}
				material={materials.Tree}
				position={[3.715, 0.099, 0.987]}
				scale={0.807}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass011.geometry}
				material={materials.Tree}
				position={[1.975, 0.099, 0.646]}
				scale={0.529}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass004.geometry}
				material={materials.Tree}
				position={[1.394, 0.099, 2.685]}
				scale={0.933}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass005.geometry}
				material={materials.Tree}
				position={[-2.473, 0.099, 3.211]}
				scale={0.933}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass006.geometry}
				material={materials.Tree}
				position={[-2.873, 0.099, -3.635]}
				scale={0.999}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass007.geometry}
				material={materials.Tree}
				position={[-3.411, 0.099, -3.145]}
				rotation={[-0.34, -0.325, 0.107]}
				scale={1.281}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass008.geometry}
				material={materials.Tree}
				position={[-2.935, 0.099, 2.536]}
				scale={0.933}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass009.geometry}
				material={materials.Tree}
				position={[-3.596, 0.099, 3.181]}
				scale={0.933}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Grass.geometry}
				material={materials.Tree}
				position={[-2.09, 0.099, 1.191]}
				scale={0.933}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Bench.geometry}
				material={materials.wood}
				position={[2.727, 0.646, 2.433]}
				scale={[0.753, 0.91, 0.322]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Vert002.geometry}
					material={materials.Metal}
					position={[0, -0.547, 0]}
					scale={[1.209, 1, 2.827]}
				/>
			</mesh>
			<group
				position={[1.77, 0.099, 1.355]}
				scale={[0.941, 1, 0.941]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle.geometry}
					material={materials.Metal}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle_1.geometry}
					material={materials.Light}
				/>
			</group>
			<group position={[-2.574, 0.099, -2.137]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle_2.geometry}
					material={materials.Metal}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle_3.geometry}
					material={materials.Light}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane.geometry}
				material={materials.Rock}
				position={[0, 0.013, 0]}
				scale={[1.057, 1, 1]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane004.geometry}
				material={materials.Water}
				position={[0, 0.086, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Bush002.geometry}
				material={materials.Tree}
				position={[3.456, 0.68, -3.095]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={1.112}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile.geometry}
				material={materials.Rock}
				position={[-0.468, 0, 2.046]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile001.geometry}
				material={materials.Rock}
				position={[-0.305, 0, 2.296]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile002.geometry}
				material={materials.Rock}
				position={[0.328, 0, 2.008]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile003.geometry}
				material={materials.Rock}
				position={[0.069, 0, 1.797]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile004.geometry}
				material={materials.Rock}
				position={[0.175, 0, 2.277]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile005.geometry}
				material={materials.Rock}
				position={[0.021, 0, 2.545]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile006.geometry}
				material={materials.Rock}
				position={[0.296, -0.02, 2.797]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile007.geometry}
				material={materials.Rock}
				position={[0.331, -0.092, 3.119]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile008.geometry}
				material={materials.Rock}
				position={[0.642, -0.035, 2.777]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile009.geometry}
				material={materials.Rock}
				position={[0.33, -0.02, 3.071]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile010.geometry}
				material={materials.Rock}
				position={[0.676, -0.035, 3.052]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile011.geometry}
				material={materials.Rock}
				position={[0.55, -0.035, 3.315]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile012.geometry}
				material={materials.Rock}
				position={[-1.311, 0, -2.907]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile013.geometry}
				material={materials.Rock}
				position={[-0.678, 0, -3.195]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile014.geometry}
				material={materials.Rock}
				position={[-0.937, 0, -3.406]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile015.geometry}
				material={materials.Rock}
				position={[-0.831, 0, -2.926]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile016.geometry}
				material={materials.Rock}
				position={[-0.985, 0, -2.658]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile017.geometry}
				material={materials.Rock}
				position={[-0.613, 0.624, 0.591]}
				rotation={[0.171, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile018.geometry}
				material={materials.Rock}
				position={[-0.365, -0.035, -2.426]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile019.geometry}
				material={materials.Rock}
				position={[-0.578, 0.526, 0.866]}
				rotation={[0.366, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile020.geometry}
				material={materials.Rock}
				position={[-0.33, -0.035, -2.151]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile021.geometry}
				material={materials.Rock}
				position={[-0.456, -0.035, -1.888]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile022.geometry}
				material={materials.Rock}
				position={[0.572, 0.698, -0.241]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Tile023.geometry}
				material={materials.Rock}
				position={[0.606, 0.698, 0.034]}
			/>
		</group>
	);
}

useGLTF.preload("/models/SunnyPark.glb");
